// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum WatchBridgePigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// The kind of change one device is telling the other about (SOW §6).
enum WatchMutationType: Int, CaseIterable {
  case logSet = 0
  case editSet = 1
  case deleteSet = 2
  case gotoExercise = 3
  case restSet = 4
  case finish = 5
  case discard = 6
}

/// One logged set. `id` is authored by the originating device (phone or watch)
/// and is the idempotency key for the append-only set log (SOW §6).
///
/// Generated class from Pigeon that represents data sent in messages.
struct WatchSet: Hashable, CustomStringConvertible {
  var id: String
  /// The set's own exercise — so an inbound watch set is attributed by identity,
  /// not the (possibly-advanced) cursor. Critical for drop sets, whose drops
  /// arrive after the top set may have already advanced the cursor.
  var exerciseId: String
  var reps: Int64
  var weightKg: Double
  var rir: Int64
  var loggedAtMs: Int64
  /// Set-group primitive (drop set now, superset later). NULL => singleton.
  var setGroup: String? = nil
  /// Order within the group: 0 = top, 1..N = drops.
  var groupSeq: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WatchSet? {
    let id = pigeonVar_list[0] as! String
    let exerciseId = pigeonVar_list[1] as! String
    let reps = pigeonVar_list[2] as! Int64
    let weightKg = pigeonVar_list[3] as! Double
    let rir = pigeonVar_list[4] as! Int64
    let loggedAtMs = pigeonVar_list[5] as! Int64
    let setGroup: String? = nilOrValue(pigeonVar_list[6])
    let groupSeq = pigeonVar_list[7] as! Int64

    return WatchSet(
      id: id,
      exerciseId: exerciseId,
      reps: reps,
      weightKg: weightKg,
      rir: rir,
      loggedAtMs: loggedAtMs,
      setGroup: setGroup,
      groupSeq: groupSeq
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      exerciseId,
      reps,
      weightKg,
      rir,
      loggedAtMs,
      setGroup,
      groupSeq,
    ]
  }
  static func == (lhs: WatchSet, rhs: WatchSet) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return WatchBridgePigeonInternal.deepEquals(lhs.id, rhs.id) && WatchBridgePigeonInternal.deepEquals(lhs.exerciseId, rhs.exerciseId) && WatchBridgePigeonInternal.deepEquals(lhs.reps, rhs.reps) && WatchBridgePigeonInternal.deepEquals(lhs.weightKg, rhs.weightKg) && WatchBridgePigeonInternal.deepEquals(lhs.rir, rhs.rir) && WatchBridgePigeonInternal.deepEquals(lhs.loggedAtMs, rhs.loggedAtMs) && WatchBridgePigeonInternal.deepEquals(lhs.setGroup, rhs.setGroup) && WatchBridgePigeonInternal.deepEquals(lhs.groupSeq, rhs.groupSeq)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WatchSet")
    WatchBridgePigeonInternal.deepHash(value: id, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: exerciseId, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: reps, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: weightKg, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: rir, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: loggedAtMs, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: setGroup, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: groupSeq, hasher: &hasher)
  }

  public var description: String {
    return "WatchSet(id: \(String(describing: id)), exerciseId: \(String(describing: exerciseId)), reps: \(String(describing: reps)), weightKg: \(String(describing: weightKg)), rir: \(String(describing: rir)), loggedAtMs: \(String(describing: loggedAtMs)), setGroup: \(String(describing: setGroup)), groupSeq: \(String(describing: groupSeq)))"
  }
}

/// One slot in the workout queue, flattened for the watch.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WatchExercise: Hashable, CustomStringConvertible {
  var programExerciseId: String
  var exerciseId: String
  var name: String
  var targetSets: Int64
  var targetRepsMin: Int64
  var targetRepsMax: Int64
  var defaultWeightKg: Double
  /// Per-exercise weight step in kg; null => caller falls back to the unit
  /// default.
  var weightStepKg: Double? = nil
  /// True when this slot was substituted on the phone (read-only "SUBSTITUTED"
  /// badge on the watch; swapping is phone-only).
  var isOverridden: Bool
  /// True when this slot was skipped for the session on the phone (skip is
  /// phone-only, like swapping). The watch renders it struck-through and walks
  /// its cursor past it; the slot stays in the queue so indices line up.
  var skipped: Bool
  /// 0 = normal; N ≥ 1 = each working set is a drop set with N drops after the
  /// top. The watch extends its logger with reps+weight page(s) per drop.
  var dropCount: Int64
  var loggedSets: [WatchSet]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WatchExercise? {
    let programExerciseId = pigeonVar_list[0] as! String
    let exerciseId = pigeonVar_list[1] as! String
    let name = pigeonVar_list[2] as! String
    let targetSets = pigeonVar_list[3] as! Int64
    let targetRepsMin = pigeonVar_list[4] as! Int64
    let targetRepsMax = pigeonVar_list[5] as! Int64
    let defaultWeightKg = pigeonVar_list[6] as! Double
    let weightStepKg: Double? = nilOrValue(pigeonVar_list[7])
    let isOverridden = pigeonVar_list[8] as! Bool
    let skipped = pigeonVar_list[9] as! Bool
    let dropCount = pigeonVar_list[10] as! Int64
    let loggedSets = pigeonVar_list[11] as! [WatchSet]

    return WatchExercise(
      programExerciseId: programExerciseId,
      exerciseId: exerciseId,
      name: name,
      targetSets: targetSets,
      targetRepsMin: targetRepsMin,
      targetRepsMax: targetRepsMax,
      defaultWeightKg: defaultWeightKg,
      weightStepKg: weightStepKg,
      isOverridden: isOverridden,
      skipped: skipped,
      dropCount: dropCount,
      loggedSets: loggedSets
    )
  }
  func toList() -> [Any?] {
    return [
      programExerciseId,
      exerciseId,
      name,
      targetSets,
      targetRepsMin,
      targetRepsMax,
      defaultWeightKg,
      weightStepKg,
      isOverridden,
      skipped,
      dropCount,
      loggedSets,
    ]
  }
  static func == (lhs: WatchExercise, rhs: WatchExercise) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return WatchBridgePigeonInternal.deepEquals(lhs.programExerciseId, rhs.programExerciseId) && WatchBridgePigeonInternal.deepEquals(lhs.exerciseId, rhs.exerciseId) && WatchBridgePigeonInternal.deepEquals(lhs.name, rhs.name) && WatchBridgePigeonInternal.deepEquals(lhs.targetSets, rhs.targetSets) && WatchBridgePigeonInternal.deepEquals(lhs.targetRepsMin, rhs.targetRepsMin) && WatchBridgePigeonInternal.deepEquals(lhs.targetRepsMax, rhs.targetRepsMax) && WatchBridgePigeonInternal.deepEquals(lhs.defaultWeightKg, rhs.defaultWeightKg) && WatchBridgePigeonInternal.deepEquals(lhs.weightStepKg, rhs.weightStepKg) && WatchBridgePigeonInternal.deepEquals(lhs.isOverridden, rhs.isOverridden) && WatchBridgePigeonInternal.deepEquals(lhs.skipped, rhs.skipped) && WatchBridgePigeonInternal.deepEquals(lhs.dropCount, rhs.dropCount) && WatchBridgePigeonInternal.deepEquals(lhs.loggedSets, rhs.loggedSets)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WatchExercise")
    WatchBridgePigeonInternal.deepHash(value: programExerciseId, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: exerciseId, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: name, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: targetSets, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: targetRepsMin, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: targetRepsMax, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: defaultWeightKg, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: weightStepKg, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: isOverridden, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: skipped, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: dropCount, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: loggedSets, hasher: &hasher)
  }

  public var description: String {
    return "WatchExercise(programExerciseId: \(String(describing: programExerciseId)), exerciseId: \(String(describing: exerciseId)), name: \(String(describing: name)), targetSets: \(String(describing: targetSets)), targetRepsMin: \(String(describing: targetRepsMin)), targetRepsMax: \(String(describing: targetRepsMax)), defaultWeightKg: \(String(describing: defaultWeightKg)), weightStepKg: \(String(describing: weightStepKg)), isOverridden: \(String(describing: isOverridden)), skipped: \(String(describing: skipped)), dropCount: \(String(describing: dropCount)), loggedSets: \(String(describing: loggedSets)))"
  }
}

/// The full state-of-record pushed phone -> watch. A flattened projection of
/// `ActiveSession` + rest timer + settings.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WatchSessionSnapshot: Hashable, CustomStringConvertible {
  /// Bump on contract change; the watch ignores unknown newer versions.
  var schemaVersion: Int64
  /// Null => no active workout (idle state on the watch).
  var sessionId: String? = nil
  var programDayName: String
  /// elapsed = now - startedAtMs, rendered locally on each device.
  var startedAtMs: Int64
  /// "kg" | "lb" — the watch formats kg weights into this display unit.
  var unit: String
  /// User accent forwarded as 0xAARRGGBB (same scheme as the Live Activity).
  var accentArgb: Int64
  var accentInkArgb: Int64
  var cursorExerciseIdx: Int64
  /// 0 => no active rest; both devices render the countdown locally.
  var restEndsAtMs: Int64
  /// Default rest length in seconds, so the watch can auto-start rest after a
  /// logged set (mirrors the phone setting).
  var restDefaultSeconds: Int64
  /// Empty-bar weight in kg (mirrors the phone setting), so the watch can
  /// compute the per-side plate breakdown offline.
  var barWeightKg: Double
  /// Available plate denominations in kg (mirrors the phone setting), so the
  /// watch can solve the per-side plate breakdown offline.
  var plateInventoryKg: [Double]
  var queue: [WatchExercise]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WatchSessionSnapshot? {
    let schemaVersion = pigeonVar_list[0] as! Int64
    let sessionId: String? = nilOrValue(pigeonVar_list[1])
    let programDayName = pigeonVar_list[2] as! String
    let startedAtMs = pigeonVar_list[3] as! Int64
    let unit = pigeonVar_list[4] as! String
    let accentArgb = pigeonVar_list[5] as! Int64
    let accentInkArgb = pigeonVar_list[6] as! Int64
    let cursorExerciseIdx = pigeonVar_list[7] as! Int64
    let restEndsAtMs = pigeonVar_list[8] as! Int64
    let restDefaultSeconds = pigeonVar_list[9] as! Int64
    let barWeightKg = pigeonVar_list[10] as! Double
    let plateInventoryKg = pigeonVar_list[11] as! [Double]
    let queue = pigeonVar_list[12] as! [WatchExercise]

    return WatchSessionSnapshot(
      schemaVersion: schemaVersion,
      sessionId: sessionId,
      programDayName: programDayName,
      startedAtMs: startedAtMs,
      unit: unit,
      accentArgb: accentArgb,
      accentInkArgb: accentInkArgb,
      cursorExerciseIdx: cursorExerciseIdx,
      restEndsAtMs: restEndsAtMs,
      restDefaultSeconds: restDefaultSeconds,
      barWeightKg: barWeightKg,
      plateInventoryKg: plateInventoryKg,
      queue: queue
    )
  }
  func toList() -> [Any?] {
    return [
      schemaVersion,
      sessionId,
      programDayName,
      startedAtMs,
      unit,
      accentArgb,
      accentInkArgb,
      cursorExerciseIdx,
      restEndsAtMs,
      restDefaultSeconds,
      barWeightKg,
      plateInventoryKg,
      queue,
    ]
  }
  static func == (lhs: WatchSessionSnapshot, rhs: WatchSessionSnapshot) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return WatchBridgePigeonInternal.deepEquals(lhs.schemaVersion, rhs.schemaVersion) && WatchBridgePigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && WatchBridgePigeonInternal.deepEquals(lhs.programDayName, rhs.programDayName) && WatchBridgePigeonInternal.deepEquals(lhs.startedAtMs, rhs.startedAtMs) && WatchBridgePigeonInternal.deepEquals(lhs.unit, rhs.unit) && WatchBridgePigeonInternal.deepEquals(lhs.accentArgb, rhs.accentArgb) && WatchBridgePigeonInternal.deepEquals(lhs.accentInkArgb, rhs.accentInkArgb) && WatchBridgePigeonInternal.deepEquals(lhs.cursorExerciseIdx, rhs.cursorExerciseIdx) && WatchBridgePigeonInternal.deepEquals(lhs.restEndsAtMs, rhs.restEndsAtMs) && WatchBridgePigeonInternal.deepEquals(lhs.restDefaultSeconds, rhs.restDefaultSeconds) && WatchBridgePigeonInternal.deepEquals(lhs.barWeightKg, rhs.barWeightKg) && WatchBridgePigeonInternal.deepEquals(lhs.plateInventoryKg, rhs.plateInventoryKg) && WatchBridgePigeonInternal.deepEquals(lhs.queue, rhs.queue)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WatchSessionSnapshot")
    WatchBridgePigeonInternal.deepHash(value: schemaVersion, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: programDayName, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: startedAtMs, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: unit, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: accentArgb, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: accentInkArgb, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: cursorExerciseIdx, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: restEndsAtMs, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: restDefaultSeconds, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: barWeightKg, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: plateInventoryKg, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: queue, hasher: &hasher)
  }

  public var description: String {
    return "WatchSessionSnapshot(schemaVersion: \(String(describing: schemaVersion)), sessionId: \(String(describing: sessionId)), programDayName: \(String(describing: programDayName)), startedAtMs: \(String(describing: startedAtMs)), unit: \(String(describing: unit)), accentArgb: \(String(describing: accentArgb)), accentInkArgb: \(String(describing: accentInkArgb)), cursorExerciseIdx: \(String(describing: cursorExerciseIdx)), restEndsAtMs: \(String(describing: restEndsAtMs)), restDefaultSeconds: \(String(describing: restDefaultSeconds)), barWeightKg: \(String(describing: barWeightKg)), plateInventoryKg: \(String(describing: plateInventoryKg)), queue: \(String(describing: queue)))"
  }
}

/// A single change event. Append-only set log + LWW for edits/cursor/rest.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WatchMutation: Hashable, CustomStringConvertible {
  var type: WatchMutationType
  var sessionId: String
  /// "watch" | "phone" — merge attribution.
  var deviceId: String
  /// Per-device monotonic counter; dedupe + ordering.
  var seq: Int64
  /// Wall clock; LWW tiebreaker for edits/cursor/rest.
  var timestampMs: Int64
  /// logSet / editSet — the set (its `id` authored by the originator).
  var set: WatchSet? = nil
  /// deleteSet — which set to remove.
  var setId: String? = nil
  /// gotoExercise — target queue index.
  var exerciseIdx: Int64? = nil
  /// restSet — new rest end (epoch ms); 0 => cancel rest.
  var restEndsAtMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WatchMutation? {
    let type = pigeonVar_list[0] as! WatchMutationType
    let sessionId = pigeonVar_list[1] as! String
    let deviceId = pigeonVar_list[2] as! String
    let seq = pigeonVar_list[3] as! Int64
    let timestampMs = pigeonVar_list[4] as! Int64
    let set: WatchSet? = nilOrValue(pigeonVar_list[5])
    let setId: String? = nilOrValue(pigeonVar_list[6])
    let exerciseIdx: Int64? = nilOrValue(pigeonVar_list[7])
    let restEndsAtMs: Int64? = nilOrValue(pigeonVar_list[8])

    return WatchMutation(
      type: type,
      sessionId: sessionId,
      deviceId: deviceId,
      seq: seq,
      timestampMs: timestampMs,
      set: set,
      setId: setId,
      exerciseIdx: exerciseIdx,
      restEndsAtMs: restEndsAtMs
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      sessionId,
      deviceId,
      seq,
      timestampMs,
      set,
      setId,
      exerciseIdx,
      restEndsAtMs,
    ]
  }
  static func == (lhs: WatchMutation, rhs: WatchMutation) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return WatchBridgePigeonInternal.deepEquals(lhs.type, rhs.type) && WatchBridgePigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && WatchBridgePigeonInternal.deepEquals(lhs.deviceId, rhs.deviceId) && WatchBridgePigeonInternal.deepEquals(lhs.seq, rhs.seq) && WatchBridgePigeonInternal.deepEquals(lhs.timestampMs, rhs.timestampMs) && WatchBridgePigeonInternal.deepEquals(lhs.set, rhs.set) && WatchBridgePigeonInternal.deepEquals(lhs.setId, rhs.setId) && WatchBridgePigeonInternal.deepEquals(lhs.exerciseIdx, rhs.exerciseIdx) && WatchBridgePigeonInternal.deepEquals(lhs.restEndsAtMs, rhs.restEndsAtMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WatchMutation")
    WatchBridgePigeonInternal.deepHash(value: type, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: deviceId, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: seq, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: timestampMs, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: set, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: setId, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: exerciseIdx, hasher: &hasher)
    WatchBridgePigeonInternal.deepHash(value: restEndsAtMs, hasher: &hasher)
  }

  public var description: String {
    return "WatchMutation(type: \(String(describing: type)), sessionId: \(String(describing: sessionId)), deviceId: \(String(describing: deviceId)), seq: \(String(describing: seq)), timestampMs: \(String(describing: timestampMs)), set: \(String(describing: set)), setId: \(String(describing: setId)), exerciseIdx: \(String(describing: exerciseIdx)), restEndsAtMs: \(String(describing: restEndsAtMs)))"
  }
}

private class WatchBridgePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WatchMutationType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return WatchSet.fromList(self.readValue() as! [Any?])
    case 131:
      return WatchExercise.fromList(self.readValue() as! [Any?])
    case 132:
      return WatchSessionSnapshot.fromList(self.readValue() as! [Any?])
    case 133:
      return WatchMutation.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class WatchBridgePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? WatchMutationType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? WatchSet {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? WatchExercise {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? WatchSessionSnapshot {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? WatchMutation {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class WatchBridgePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return WatchBridgePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return WatchBridgePigeonCodecWriter(data: data)
  }
}

class WatchBridgePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = WatchBridgePigeonCodec(readerWriter: WatchBridgePigeonCodecReaderWriter())
}

/// Dart -> Swift. Implemented natively by the WCSession manager in the Runner.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WatchBridgeHostApi {
  /// Configure this device's WCSession and activate it. Safe to call repeatedly.
  func activate() throws
  /// Whether an Apple Watch is currently paired with this iPhone.
  func isPaired() throws -> Bool
  /// Whether the watch app counterpart is currently reachable.
  func isReachable() throws -> Bool
  /// Push the authoritative session snapshot to the watch (applicationContext +
  /// App-Group stash, plus an instant sendMessage when reachable). Pass a
  /// snapshot with a null `sessionId` to signal "no active workout".
  func pushSnapshot(snapshot: WatchSessionSnapshot) throws
  /// Send a phone-originated mutation to the watch (e.g. the user logged a set
  /// on the phone while the watch is connected).
  func sendMutation(mutation: WatchMutation) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WatchBridgeHostApiSetup {
  static var codec: FlutterStandardMessageCodec { WatchBridgePigeonCodec.shared }
  /// Sets up an instance of `WatchBridgeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WatchBridgeHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Configure this device's WCSession and activate it. Safe to call repeatedly.
    let activateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ls_workout_tracker.WatchBridgeHostApi.activate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      activateChannel.setMessageHandler { _, reply in
        do {
          try api.activate()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      activateChannel.setMessageHandler(nil)
    }
    /// Whether an Apple Watch is currently paired with this iPhone.
    let isPairedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ls_workout_tracker.WatchBridgeHostApi.isPaired\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isPairedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isPaired()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isPairedChannel.setMessageHandler(nil)
    }
    /// Whether the watch app counterpart is currently reachable.
    let isReachableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ls_workout_tracker.WatchBridgeHostApi.isReachable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isReachableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isReachable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isReachableChannel.setMessageHandler(nil)
    }
    /// Push the authoritative session snapshot to the watch (applicationContext +
    /// App-Group stash, plus an instant sendMessage when reachable). Pass a
    /// snapshot with a null `sessionId` to signal "no active workout".
    let pushSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ls_workout_tracker.WatchBridgeHostApi.pushSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pushSnapshotChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let snapshotArg = args[0] as! WatchSessionSnapshot
        do {
          try api.pushSnapshot(snapshot: snapshotArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pushSnapshotChannel.setMessageHandler(nil)
    }
    /// Send a phone-originated mutation to the watch (e.g. the user logged a set
    /// on the phone while the watch is connected).
    let sendMutationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ls_workout_tracker.WatchBridgeHostApi.sendMutation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMutationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mutationArg = args[0] as! WatchMutation
        do {
          try api.sendMutation(mutation: mutationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendMutationChannel.setMessageHandler(nil)
    }
  }
}

/// Swift -> Dart. Implemented in Dart by the watch sync controller; the native
/// side calls these when WatchConnectivity events arrive.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol WatchBridgeFlutterApiProtocol {
  /// A mutation arrived from the watch (via sendMessage or transferUserInfo).
  func onMutationReceived(mutation mutationArg: WatchMutation, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// The watch asked for a fresh snapshot (cold launch / reconnect).
  func onWatchRequestedResync(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// The watch's reachability changed.
  func onReachabilityChanged(reachable reachableArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// The watch app opened onto an active session (used to light the phone-side
  /// "watch connected" indicator).
  func onWatchJoinedSession(sessionId sessionIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class WatchBridgeFlutterApi: WatchBridgeFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: WatchBridgePigeonCodec {
    return WatchBridgePigeonCodec.shared
  }
  /// A mutation arrived from the watch (via sendMessage or transferUserInfo).
  func onMutationReceived(mutation mutationArg: WatchMutation, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ls_workout_tracker.WatchBridgeFlutterApi.onMutationReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([mutationArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// The watch asked for a fresh snapshot (cold launch / reconnect).
  func onWatchRequestedResync(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ls_workout_tracker.WatchBridgeFlutterApi.onWatchRequestedResync\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// The watch's reachability changed.
  func onReachabilityChanged(reachable reachableArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ls_workout_tracker.WatchBridgeFlutterApi.onReachabilityChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([reachableArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// The watch app opened onto an active session (used to light the phone-side
  /// "watch connected" indicator).
  func onWatchJoinedSession(sessionId sessionIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ls_workout_tracker.WatchBridgeFlutterApi.onWatchJoinedSession\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
