// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// The kind of change one device is telling the other about (SOW §6).
enum WatchMutationType {
  logSet,
  editSet,
  deleteSet,
  gotoExercise,
  restSet,
  finish,
  discard,
}

/// One logged set. `id` is authored by the originating device (phone or watch)
/// and is the idempotency key for the append-only set log (SOW §6).
class WatchSet {
  WatchSet({
    required this.id,
    required this.reps,
    required this.weightKg,
    required this.rir,
    required this.loggedAtMs,
  });

  String id;

  int reps;

  double weightKg;

  int rir;

  int loggedAtMs;

  List<Object?> _toList() {
    return <Object?>[
      id,
      reps,
      weightKg,
      rir,
      loggedAtMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static WatchSet decode(Object result) {
    result as List<Object?>;
    return WatchSet(
      id: result[0]! as String,
      reps: result[1]! as int,
      weightKg: result[2]! as double,
      rir: result[3]! as int,
      loggedAtMs: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WatchSet || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(reps, other.reps) && _deepEquals(weightKg, other.weightKg) && _deepEquals(rir, other.rir) && _deepEquals(loggedAtMs, other.loggedAtMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WatchSet(id: $id, reps: $reps, weightKg: $weightKg, rir: $rir, loggedAtMs: $loggedAtMs)';
  }
}

/// One slot in the workout queue, flattened for the watch.
class WatchExercise {
  WatchExercise({
    required this.programExerciseId,
    required this.exerciseId,
    required this.name,
    required this.targetSets,
    required this.targetRepsMin,
    required this.targetRepsMax,
    required this.defaultWeightKg,
    this.weightStepKg,
    required this.isOverridden,
    required this.loggedSets,
  });

  String programExerciseId;

  String exerciseId;

  String name;

  int targetSets;

  int targetRepsMin;

  int targetRepsMax;

  double defaultWeightKg;

  /// Per-exercise weight step in kg; null => caller falls back to the unit
  /// default.
  double? weightStepKg;

  /// True when this slot was substituted on the phone (read-only "SUBSTITUTED"
  /// badge on the watch; swapping is phone-only).
  bool isOverridden;

  List<WatchSet> loggedSets;

  List<Object?> _toList() {
    return <Object?>[
      programExerciseId,
      exerciseId,
      name,
      targetSets,
      targetRepsMin,
      targetRepsMax,
      defaultWeightKg,
      weightStepKg,
      isOverridden,
      loggedSets,
    ];
  }

  Object encode() {
    return _toList();  }

  static WatchExercise decode(Object result) {
    result as List<Object?>;
    return WatchExercise(
      programExerciseId: result[0]! as String,
      exerciseId: result[1]! as String,
      name: result[2]! as String,
      targetSets: result[3]! as int,
      targetRepsMin: result[4]! as int,
      targetRepsMax: result[5]! as int,
      defaultWeightKg: result[6]! as double,
      weightStepKg: result[7] as double?,
      isOverridden: result[8]! as bool,
      loggedSets: (result[9]! as List<Object?>).cast<WatchSet>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WatchExercise || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(programExerciseId, other.programExerciseId) && _deepEquals(exerciseId, other.exerciseId) && _deepEquals(name, other.name) && _deepEquals(targetSets, other.targetSets) && _deepEquals(targetRepsMin, other.targetRepsMin) && _deepEquals(targetRepsMax, other.targetRepsMax) && _deepEquals(defaultWeightKg, other.defaultWeightKg) && _deepEquals(weightStepKg, other.weightStepKg) && _deepEquals(isOverridden, other.isOverridden) && _deepEquals(loggedSets, other.loggedSets);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WatchExercise(programExerciseId: $programExerciseId, exerciseId: $exerciseId, name: $name, targetSets: $targetSets, targetRepsMin: $targetRepsMin, targetRepsMax: $targetRepsMax, defaultWeightKg: $defaultWeightKg, weightStepKg: $weightStepKg, isOverridden: $isOverridden, loggedSets: $loggedSets)';
  }
}

/// The full state-of-record pushed phone -> watch. A flattened projection of
/// `ActiveSession` + rest timer + settings.
class WatchSessionSnapshot {
  WatchSessionSnapshot({
    required this.schemaVersion,
    this.sessionId,
    required this.programDayName,
    required this.startedAtMs,
    required this.unit,
    required this.accentArgb,
    required this.accentInkArgb,
    required this.cursorExerciseIdx,
    required this.restEndsAtMs,
    required this.restDefaultSeconds,
    required this.queue,
  });

  /// Bump on contract change; the watch ignores unknown newer versions.
  int schemaVersion;

  /// Null => no active workout (idle state on the watch).
  String? sessionId;

  String programDayName;

  /// elapsed = now - startedAtMs, rendered locally on each device.
  int startedAtMs;

  /// "kg" | "lb" — the watch formats kg weights into this display unit.
  String unit;

  /// User accent forwarded as 0xAARRGGBB (same scheme as the Live Activity).
  int accentArgb;

  int accentInkArgb;

  int cursorExerciseIdx;

  /// 0 => no active rest; both devices render the countdown locally.
  int restEndsAtMs;

  /// Default rest length in seconds, so the watch can auto-start rest after a
  /// logged set (mirrors the phone setting).
  int restDefaultSeconds;

  List<WatchExercise> queue;

  List<Object?> _toList() {
    return <Object?>[
      schemaVersion,
      sessionId,
      programDayName,
      startedAtMs,
      unit,
      accentArgb,
      accentInkArgb,
      cursorExerciseIdx,
      restEndsAtMs,
      restDefaultSeconds,
      queue,
    ];
  }

  Object encode() {
    return _toList();  }

  static WatchSessionSnapshot decode(Object result) {
    result as List<Object?>;
    return WatchSessionSnapshot(
      schemaVersion: result[0]! as int,
      sessionId: result[1] as String?,
      programDayName: result[2]! as String,
      startedAtMs: result[3]! as int,
      unit: result[4]! as String,
      accentArgb: result[5]! as int,
      accentInkArgb: result[6]! as int,
      cursorExerciseIdx: result[7]! as int,
      restEndsAtMs: result[8]! as int,
      restDefaultSeconds: result[9]! as int,
      queue: (result[10]! as List<Object?>).cast<WatchExercise>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WatchSessionSnapshot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(schemaVersion, other.schemaVersion) && _deepEquals(sessionId, other.sessionId) && _deepEquals(programDayName, other.programDayName) && _deepEquals(startedAtMs, other.startedAtMs) && _deepEquals(unit, other.unit) && _deepEquals(accentArgb, other.accentArgb) && _deepEquals(accentInkArgb, other.accentInkArgb) && _deepEquals(cursorExerciseIdx, other.cursorExerciseIdx) && _deepEquals(restEndsAtMs, other.restEndsAtMs) && _deepEquals(restDefaultSeconds, other.restDefaultSeconds) && _deepEquals(queue, other.queue);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WatchSessionSnapshot(schemaVersion: $schemaVersion, sessionId: $sessionId, programDayName: $programDayName, startedAtMs: $startedAtMs, unit: $unit, accentArgb: $accentArgb, accentInkArgb: $accentInkArgb, cursorExerciseIdx: $cursorExerciseIdx, restEndsAtMs: $restEndsAtMs, restDefaultSeconds: $restDefaultSeconds, queue: $queue)';
  }
}

/// A single change event. Append-only set log + LWW for edits/cursor/rest.
class WatchMutation {
  WatchMutation({
    required this.type,
    required this.sessionId,
    required this.deviceId,
    required this.seq,
    required this.timestampMs,
    this.set,
    this.setId,
    this.exerciseIdx,
    this.restEndsAtMs,
  });

  WatchMutationType type;

  String sessionId;

  /// "watch" | "phone" — merge attribution.
  String deviceId;

  /// Per-device monotonic counter; dedupe + ordering.
  int seq;

  /// Wall clock; LWW tiebreaker for edits/cursor/rest.
  int timestampMs;

  /// logSet / editSet — the set (its `id` authored by the originator).
  WatchSet? set;

  /// deleteSet — which set to remove.
  String? setId;

  /// gotoExercise — target queue index.
  int? exerciseIdx;

  /// restSet — new rest end (epoch ms); 0 => cancel rest.
  int? restEndsAtMs;

  List<Object?> _toList() {
    return <Object?>[
      type,
      sessionId,
      deviceId,
      seq,
      timestampMs,
      set,
      setId,
      exerciseIdx,
      restEndsAtMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static WatchMutation decode(Object result) {
    result as List<Object?>;
    return WatchMutation(
      type: result[0]! as WatchMutationType,
      sessionId: result[1]! as String,
      deviceId: result[2]! as String,
      seq: result[3]! as int,
      timestampMs: result[4]! as int,
      set: result[5] as WatchSet?,
      setId: result[6] as String?,
      exerciseIdx: result[7] as int?,
      restEndsAtMs: result[8] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WatchMutation || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(sessionId, other.sessionId) && _deepEquals(deviceId, other.deviceId) && _deepEquals(seq, other.seq) && _deepEquals(timestampMs, other.timestampMs) && _deepEquals(set, other.set) && _deepEquals(setId, other.setId) && _deepEquals(exerciseIdx, other.exerciseIdx) && _deepEquals(restEndsAtMs, other.restEndsAtMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WatchMutation(type: $type, sessionId: $sessionId, deviceId: $deviceId, seq: $seq, timestampMs: $timestampMs, set: $set, setId: $setId, exerciseIdx: $exerciseIdx, restEndsAtMs: $restEndsAtMs)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is WatchMutationType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is WatchSet) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is WatchExercise) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is WatchSessionSnapshot) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is WatchMutation) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : WatchMutationType.values[value];
      case 130:
        return WatchSet.decode(readValue(buffer)!);
      case 131:
        return WatchExercise.decode(readValue(buffer)!);
      case 132:
        return WatchSessionSnapshot.decode(readValue(buffer)!);
      case 133:
        return WatchMutation.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart -> Swift. Implemented natively by the WCSession manager in the Runner.
class WatchBridgeHostApi {
  /// Constructor for [WatchBridgeHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WatchBridgeHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Configure this device's WCSession and activate it. Safe to call repeatedly.
  Future<void> activate() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ls_workout_tracker.WatchBridgeHostApi.activate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Whether an Apple Watch is currently paired with this iPhone.
  Future<bool> isPaired() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ls_workout_tracker.WatchBridgeHostApi.isPaired$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Whether the watch app counterpart is currently reachable.
  Future<bool> isReachable() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ls_workout_tracker.WatchBridgeHostApi.isReachable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Push the authoritative session snapshot to the watch (applicationContext +
  /// App-Group stash, plus an instant sendMessage when reachable). Pass a
  /// snapshot with a null `sessionId` to signal "no active workout".
  Future<void> pushSnapshot(WatchSessionSnapshot snapshot) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ls_workout_tracker.WatchBridgeHostApi.pushSnapshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[snapshot]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Send a phone-originated mutation to the watch (e.g. the user logged a set
  /// on the phone while the watch is connected).
  Future<void> sendMutation(WatchMutation mutation) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ls_workout_tracker.WatchBridgeHostApi.sendMutation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mutation]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Swift -> Dart. Implemented in Dart by the watch sync controller; the native
/// side calls these when WatchConnectivity events arrive.
abstract class WatchBridgeFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// A mutation arrived from the watch (via sendMessage or transferUserInfo).
  void onMutationReceived(WatchMutation mutation);

  /// The watch asked for a fresh snapshot (cold launch / reconnect).
  void onWatchRequestedResync();

  /// The watch's reachability changed.
  void onReachabilityChanged(bool reachable);

  /// The watch app opened onto an active session (used to light the phone-side
  /// "watch connected" indicator).
  void onWatchJoinedSession(String sessionId);

  static void setUp(WatchBridgeFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ls_workout_tracker.WatchBridgeFlutterApi.onMutationReceived$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final WatchMutation arg_mutation = args[0]! as WatchMutation;
          try {
            api.onMutationReceived(arg_mutation);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ls_workout_tracker.WatchBridgeFlutterApi.onWatchRequestedResync$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onWatchRequestedResync();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ls_workout_tracker.WatchBridgeFlutterApi.onReachabilityChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_reachable = args[0]! as bool;
          try {
            api.onReachabilityChanged(arg_reachable);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ls_workout_tracker.WatchBridgeFlutterApi.onWatchJoinedSession$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_sessionId = args[0]! as String;
          try {
            api.onWatchJoinedSession(arg_sessionId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
